version: 2
jobs:
  build:
    docker:
      - image: acemod/armake
    steps:
      - checkout
      - run:
          name: Validate SQF And Config style
          command: python tools/sqf_validator.py && python tools/config_style_checker.py
      - run:
          name: Build
          command: armake --version
      - deploy:
          name: Circle build test
          command: |
            if [ "${CIRCLE_BRANCH}" == "rc" ] && [ "${CIRCLE_PROJECT_USERNAME}" == "grester" ]; then
              pip install pygithub pygithub3
              python3 tools/deploy.py
            else
              echo "Skipping, not on grester/VPHUD rc branch..."
            fi
